<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Akanshas-MacBook-Pro.local" name="testCases.feedbackTestCases" tests="6" failures="1" timestamp="26 Sep 2018 06:21:09 GMT" time="346.548" errors="0">
  <testcase name="validateFeedbackPage" time="16.885" classname="testCases.feedbackTestCases"/>
  <testcase name="validateNoLocationAvailable" time="42.584" classname="testCases.feedbackTestCases">
    <failure type="java.lang.AssertionError" message="expected [We couldn&#039;t find any stations near this location.] but found []">
      <![CDATA[java.lang.AssertionError: expected [We couldn't find any stations near this location.] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at chevronClass.displayMessages.Assert(displayMessages.java:16)
at chevronClass.feedbackPage.verifyNoListIfLocationUnavailable(feedbackPage.java:32)
at testCases.feedbackTestCases.validateNoLocationAvailable(feedbackTestCases.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateNoLocationAvailable -->
  <testcase name="verifySearchStation" time="38.922" classname="testCases.feedbackTestCases"/>
  <testcase name="verifyDoneButton" time="53.637" classname="testCases.feedbackTestCases"/>
  <testcase name="fillTheForm" time="93.822" classname="testCases.feedbackTestCases"/>
  <testcase name="checkDialer" time="100.698" classname="testCases.feedbackTestCases"/>
</testsuite> <!-- testCases.feedbackTestCases -->
